/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 wheel.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/models/wheels/default/wheel.gltf')
  //const { actions } = useAnimations(animations, group)

  const { side, axel, color = 0x222222 } = props;
  let position = [0,0,0];
  let rotation = [0,0,0];
  let scale = [1,1,1];
  const frontOffset = 3;
  const leftOffset = 0;
  const material = new THREE.MeshPhysicalMaterial({ color: color, roughness: 0.5 });
  if (side === 'left') {
    position = [-1 * leftOffset, 0, -2.5];
    rotation = [0, Math.PI, 0];    
  }
  if (axel === 'front') {
    position = [0, 0, frontOffset];
    if (side === 'left') {
      position[2] = frontOffset - 2;
    }
    scale = [0.6, 0.6, 0.6];
  }
  return (
    <group ref={group} {...props} dispose={null} position={ position } rotation={ rotation } scale={ scale }>
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={material} position={[1.865, 1.351, -1.439]} rotation={[-Math.PI / 2, 0, 0]} scale={2.321} />
    </group>
  )
}

useGLTF.preload('/assets/models/wheels/default/wheel.gltf')
