/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 wheel.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  
  const { nodes, materials } = useGLTF('./assets/models/wheels/orange/wheel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Orange001_Orange_0003.geometry} material={materials.Orange} position={[1.839, 1.7, -1.609]} rotation={[-0.59, 1.484, -2.921]} scale={1.299} />
    </group>
  )
}

useGLTF.preload('./assets/models/wheels/orange/wheel.gltf')
